### ISSUE TITLE
What is the significance of the group size?

### ISSUE THREAD

**Issue by felciano** [matthieuheitz/google-data-analyses#10]
Thank you for making this script available. I'm testing it out now and it looks like a very helpful interpretation of the Google Maps location data. 

Could you provide some clarification/explanation for how to interpret the "Group of # Points" messages, presumably in the context of the `group_size` parameter? I can't figure out if the points refer to geographic locations (e.g. a cluster of points near each other in 2D) or timepoints (i.e. a cluster of measurements close to each other in time).

**Comment by matthieuheitz** [comment]
Hi! Thank you for your interest!
So, the groups are made of samples that are close in time, and so group_size controls the time interval of one group.
So if you say group_size=1 hour, then you will have groups of points, where the first and the last in the group are no further apart than 1 hour.
And by definition of the points we search (within a given position + radius), they are also "grouped" in a geographic location: the one you input in POI.
I added this option because yes, Google maps often acquires of lot of points around the same place, at small time intervals, but it's generally not helpful to see them all.
