### ISSUE TITLE
Distinct dates

### ISSUE THREAD

**Issue by LordMyschkin** [matthieuheitz/google-data-analyses#3]
This ist great and about perfectly fitting for what I was looking quite a long time. Is there an easy way to get every date listeted only once, so I can get all the dates I've been at work AND how many times that was (I need it for Tax)?
If you say "Just do it yourself, lazy bastard" I am about to learn python to do it myself.
Strange google does not provide a simple way to access these data they are collecting.....

**Comment by matthieuheitz** [comment]
That should be pretty straightforward to add.
I'll try to do it this afternoon :)

**Comment by matthieuheitz** [comment]
Hi @LordMyschkin, I've just updated the script.
It now supports what I called "groups", which are groups of time points, which are controlled by the time interval between the first and last element of the group.
So basically, if you want to have the dates at which you've been at work, just set the group size to something like 20 hours.
If you set it to one day, then it will not put the different points in correct groups, because if on day d you went to work at 8, and on day d+1, you went to work at 7, then the timepoints from 7 to 8 on day d+1 will be grouped with the timepoints from day d.
I hope it's not too confusing, tell me if that works well for you :)

**Comment by LordMyschkin** [comment]
Thank you so much, works great! I just added a counter for the groups (my python knowledge goes that far ;-) so I can tell how often I was at work.  You were right about the grouping, 14 hours works great.
One line to count my days at work... Will greatly improve my tax calculations next year!

**Comment by matthieuheitz** [comment]
I'm glad it worked out :)
